# Generated by Django 4.2 on 2023-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='team/')),
                ('facebook_profile_link', models.URLField()),
                ('twitter_profile_link', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Our Team',
                'verbose_name_plural': 'Our Team',
                'ordering': ('-date_added',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=30)),
                ('testimony', models.TextField()),
                ('location', models.CharField(help_text='State, Country - e.g Lagos, Nigeria', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'ordering': ('-date_created',),
            },
        ),
    ]
