# Generated by Django 4.2 on 2023-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_testimony_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='testimonials/'),
        ),
    ]
