# Generated by Django 4.2 on 2023-08-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
